"""make notes and description no nullable

Revision ID: 1231278e94c0
Revises: 5dbe0b08ab89
Create Date: 2026-05-31 21:29:56.686916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1231278e94c0'
down_revision: Union[str, Sequence[str], None] = '5dbe0b08ab89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_sessions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('study_sessions', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_sessions', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('study_sessions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
