"""session checklist

Revision ID: 4443ab60dbb2
Revises: 4bc26baad091
Create Date: 2026-06-23 02:59:48.207682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4443ab60dbb2'
down_revision: Union[str, Sequence[str], None] = '4bc26baad091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
            'study_sessions',
            sa.Column(
                'checklist',
                postgresql.JSONB(astext_type=sa.Text()),
                server_default=sa.text("'[]'::jsonb"),
                nullable=False,
            ),
        )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'checklist')
    # ### end Alembic commands ###
