"""add history to pomodoros

Revision ID: 4bc26baad091
Revises: 65f1a06bcc23
Create Date: 2026-06-22 22:44:18.524429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bc26baad091'
down_revision: Union[str, Sequence[str], None] = '65f1a06bcc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_session_pomodoros', sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_session_pomodoros', 'history')
    # ### end Alembic commands ###
