"""add notes and status to study_session

Revision ID: 5dbe0b08ab89
Revises: 95990258d028
Create Date: 2026-05-31 19:29:19.111367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbe0b08ab89'
down_revision: Union[str, Sequence[str], None] = '95990258d028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

session_status_enum = sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='studysessionstatus')

def upgrade() -> None:
    """Upgrade schema."""
    session_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_sessions', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('study_sessions', sa.Column('status', session_status_enum, nullable=True))

    op.execute("""UPDATE study_sessions SET status = 'PENDING' WHERE status IS NULL""")

    op.alter_column(
        'study_sessions', 
        'status',
        nullable=False,
        existing_type=session_status_enum
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_sessions', 'status')
    op.drop_column('study_sessions', 'notes')

    session_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
