"""add more study session transition events

Revision ID: 65f1a06bcc23
Revises: c99e88d033f5
Create Date: 2026-06-17 21:18:20.630879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f1a06bcc23'
down_revision: Union[str, Sequence[str], None] = 'c99e88d033f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'STUDY_SESSION_UNDO_STARTED'"
    )

    op.execute(
        "ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'STUDY_SESSION_UNDO_CANCELED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
