"""add_status_column

Revision ID: 8b54e362c3fc
Revises: d6f357c91edf
Create Date: 2026-05-24 18:23:39.254181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b54e362c3fc'
down_revision: Union[str, Sequence[str], None] = 'd6f357c91edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('status', sa.String(), nullable=False, server_default='to_do'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'status')
    # ### end Alembic commands ###
