"""add pomodoro table

Revision ID: c337a78188e1
Revises: 27b6efb2732d
Create Date: 2026-06-03 17:44:37.124320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c337a78188e1'
down_revision: Union[str, Sequence[str], None] = '27b6efb2732d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_session_pomodoros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_session_id', sa.String(), nullable=False),
    sa.Column('state_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state_remaining_duration', sa.Interval(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'focus_mode', 'break_mode', 'pause', 'done', name='pomodorostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_session_pomodoros')
    # ### end Alembic commands ###
