"""Altera a tabela Goals

Revision ID: d6f357c91edf
Revises: 081332963bf6
Create Date: 2026-05-19 16:27:32.543661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f357c91edf'
down_revision: Union[str, Sequence[str], None] = '026a82760006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('goal_tags', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('goals', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('goals', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('goals', 'goal_type')
    op.drop_column('goals', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('goals', sa.Column('goal_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('goals', 'end_date')
    op.drop_column('goals', 'start_date')
    op.drop_column('goals', 'goal_tags')
    # ### end Alembic commands ###
