"""add events

Revision ID: e4dd627f00f3
Revises: fec1ca207901
Create Date: 2026-06-12 19:54:53.573891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4dd627f00f3'
down_revision: Union[str, Sequence[str], None] = 'fec1ca207901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('GOAL_CREATED', 'GOAL_EDITED', 'GOAL_COMPLETED', 'GOAL_DELETED', 'STUDY_SESSION_CREATED', 'STUDY_SESSION_STARTED', 'STUDY_SESSION_FINISHED', 'STUDY_SESSION_CANCELED', 'STUDY_SESSION_EVALUATED', 'STUDY_SESSION_EDITED_NOTES', 'STUDY_SESSION_ADDED_COMMENT', 'POMODORO_FOCUS_MODE_STARTED', 'POMODORO_BREAK_MODE_STARTED', 'POMODORO_PAUSED', 'POMODORO_RESUMED', 'POMODORO_RESTARTED', 'POMODORO_FINISHED', name='eventtype'), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=True),
    sa.Column('study_session_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_student_timestamp', 'events', ['student_id', 'timestamp'], unique=False)
    op.create_index('ix_events_study_session_id', 'events', ['study_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_study_session_id', table_name='events')
    op.drop_index('ix_events_student_timestamp', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
