"""add session update event

Revision ID: fbaf4db47ddd
Revises: 65f1a06bcc23
Create Date: 2026-06-18 21:29:33.148754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaf4db47ddd'
down_revision: Union[str, Sequence[str], None] = '65f1a06bcc23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'STUDY_SESSION_UPDATED'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
