"""add study session and pomodoro

Revision ID: fec1ca207901
Revises: 8b54e362c3fc
Create Date: 2026-06-04 22:33:23.973468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec1ca207901'
down_revision: Union[str, Sequence[str], None] = '8b54e362c3fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('todo', 'doing', 'done', 'canceled', name='status'), nullable=False),
    sa.Column('planned_to_start_at', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('domain_perception_level', sa.Integer(), nullable=True),
    sa.Column('learning_difficulty_level', sa.Integer(), nullable=True),
    sa.Column('strategies', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('final_comment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_active_session_per_student', 'study_sessions', ['student_id'], unique=True, postgresql_where=sa.text("status = 'doing'"))
    op.create_table('study_session_pomodoros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_session_id', sa.String(), nullable=False),
    sa.Column('focus_duration', sa.Interval(), nullable=False),
    sa.Column('break_duration', sa.Interval(), nullable=False),
    sa.Column('current_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_remaining_duration', sa.Interval(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'focus_mode', 'focus_pause', 'break_mode', 'break_pause', 'done', name='pomodorostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_session_pomodoros')
    op.drop_index('unique_active_session_per_student', table_name='study_sessions', postgresql_where=sa.text("status = 'doing'"))
    op.drop_table('study_sessions')
    # ### end Alembic commands ###
